version: "3.8"

services:
  frontend:
    image: nginx:alpine
    networks: 
      - traefik-net
    expose:
      - 80
    volumes:
      - "../frontend/html:/usr/share/nginx/html"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.demo.rule=Host(`demo.localhost`)"
    - "traefik.http.middlewares.imageopti.plugin.dev.config.processor=imaginary"
    - "traefik.http.middlewares.imageopti.plugin.dev.config.imaginary.url=http://imaginary:9000"
    - "traefik.http.middlewares.imageopti.plugin.dev.config.cache=file"
    - "traefik.http.middlewares.imageopti.plugin.dev.config.file.path=/root"
    - "traefik.http.routers.demo.middlewares=imageopti"

networks:
  traefik-net:
    external:
      name: traefik-net
