version: "3.8"

services:
  frontend:
    build: ../frontend
    networks: 
      - traefik-net
    expose:
      - 80
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.demo.rule=Host(`demo.localhost`)"
    - "traefik.http.middlewares.plugindemo.plugin.dev.foo=bar"
    - "traefik.http.routers.demo.middlewares=plugindemo"

networks:
  traefik-net:
    external:
      name: traefik-net
